apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jelle-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jelle.local
    secretName: jelle-tls-secret
  rules:
  - host: jelle.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ngnix-service-jelle
            port:
              number: 5000